services:
  code-server:
    image: ${IMAGE:-p1c2u/code-server-oss}:${TAG:-latest}
    build:
        context: .
        args:
            HTTP_PROXY: ${HTTP_PROXY:-}
            HTTPS_PROXY: ${HTTPS_PROXY:-}
    ports:
      - "${CODE_PORT:-8080}:8080"
    command: --host 0.0.0.0 --port 8080 --without-connection-token
