# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Docker image 

on:
  workflow_dispatch:
    inputs:
      vscode_tag:
        description: 'Vscode tag to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VSCODE_TAG: ${{ github.event.inputs.vscode_tag }}
        with:
          name: p1c2u/code-server-oss
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          cache: ${{ github.event_name != 'schedule' }}
          buildargs: VSCODE_TAG
          tags: "${{ github.event.inputs.vscode_tag }}"
