# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Docker image nightly

on:
  schedule:
    - cron: '0 2 * * *' # Weekly on Sundays at 02:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: metadata
        shell: bash
        run: echo "date=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VSCODE_TAG: main
        with:
          name: p1c2u/code-server-oss
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Can't build arm64 based docker image
          # See https://github.com/p1c2u/code-server-oss/issues/1
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          cache: ${{ github.event_name != 'schedule' }}
          buildargs: VSCODE_TAG
          tags: "${{ env.VSCODE_TAG }}-${{ steps.metadata.outputs.date }}"
